/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#303034',
        'surface-variant': '#353439',
        tertiary: '#ebb2ff',
        'on-tertiary-fixed-variant': '#721199',
        'on-surface': '#e5e1e7',
        'surface-bright': '#39393d',
        'inverse-surface': '#e5e1e7',
        'error-container': '#93000a',
        'inverse-primary': '#006875',
        'surface-dim': '#131317',
        'on-secondary-fixed-variant': '#544600',
        'on-primary-fixed': '#001f24',
        'on-error-container': '#ffdad6',
        'surface-container-high': '#2a292e',
        'surface-tint': '#006875',
        'tertiary-fixed-dim': '#ebb2ff',
        background: '#131317',
        primary: '#00daf3',
        'on-background': '#e5e1e7',
        'secondary-container': '#ffdb3c',
        outline: '#938f97',
        'tertiary-fixed': '#f8d8ff',
        'primary-fixed': '#9cf0ff',
        surface: '#131317',
        'surface-container-low': '#1b1b1f',
        'outline-variant': '#48464c',
        'surface-container': '#1f1f23',
        'on-error': '#690005',
        'surface-container-highest': '#353439',
        'on-secondary': '#3a3000',
        'secondary-fixed': '#ffe16d',
        'on-secondary-container': '#725f00',
        'on-tertiary': '#520071',
        'on-tertiary-container': '#ad54d3',
        'on-tertiary-fixed': '#320047',
        'on-secondary-fixed': '#221b00',
        'tertiary-container': '#1d002b',
        'secondary-fixed-dim': '#e9c400',
        'on-primary': '#00363d',
        error: '#ffb4ab',
        'primary-fixed-dim': '#00daf3',
        'on-primary-container': '#008898',
        'primary-container': '#001014',
        'on-primary-fixed-variant': '#004f58',
        'surface-container-lowest': '#0e0e12',
        secondary: '#fff9ef',
        'on-surface-variant': '#c9c5cd',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
